131 make a simulated detector that can write hdf files
bluesky/ophyd-async pull request #144
Opened 2024-03-11 09:26 UTC by stan-dot

2024-04-04 11:25 UTC, coretl requested changes
Couple of naming changes, other than that looks good

2024-04-04 11:25 UTC, coretl commented on src/ophyd_async/sim/SimPatternDetector.py
ditto

2024-04-04 11:25 UTC, coretl commented on src/ophyd_async/sim/SimPatternDetector.py
> +class SimDetector(StandardDetector):
```suggestion
class SimPatternDetector(StandardDetector):
```

2024-04-04 12:42 UTC, stan-dot commented on src/ophyd_async/sim/PatternGenerator.py
ah of course

2024-04-04 13:00 UTC, stan-dot commented on src/ophyd_async/sim/PatternGenerator.py
why not snake case? given the other files?
`src/ophyd_async/epics/
├── __init__.py
├── _backend
│   ├── __init__.py
│   ├── _aioca.py
│   └── _p4p.py
├── areadetector
│   ├── __init__.py
│   ├── controllers
│   │   ├── __init__.py
│   │   ├── ad_sim_controller.py
│   │   └── pilatus_controller.py
│   ├── drivers
│   │   ├── __init__.py
│   │   ├── ad_base.py
│   │   └── pilatus_driver.py
│   ├── single_trigger_det.py
│   ├── utils.py
│   └── writers
│       ├── __init__.py
│       ├── _hdfdataset.py
│       ├── _hdffile.py
│       ├── hdf_writer.py
│       ├── nd_file_hdf.py
│       └── nd_plugin.py
├── demo
│   ├── __init__.py
│   ├── demo_ad_sim_detector.py
│   ├── mover.db
│   └── sensor.db
├── motion
│   ├── __init__.py
│   └── motor.py
└── signal
    ├── __init__.py
    ├── _epics_transport.py
    ├── pvi_get.py
    └── signal.py

9 directories, 29 files`

2024-04-04 13:00 UTC, stan-dot commented on src/ophyd_async/sim/SimPatternDetector.py
> +class SimDetector(StandardDetector):
done

2024-04-04 13:04 UTC, coretl commented on src/ophyd_async/sim/PatternGenerator.py
PEP8 says snake case is also fine for modules (although not for packages), so `pattern_generator.py` is fine

2024-04-04 13:32 UTC, stan-dot commented on src/ophyd_async/sim/PatternGenerator.py
ok will do after the meeting

2024-04-15 09:33 UTC, coretl approved these changes

2024-04-15 10:24 UTC, stan-dot commented
that issue is still present with pyside6 at 6.7.0
https://bugreports.qt.io/browse/PYSIDE-2665?jql=text%20~%20"unexpected%20indent%22

2024-04-15 10:31 UTC, merged