Fix docs and tidy README
bluesky/ophyd-async pull request #272
Opened 2024-04-30 15:28 UTC by coretl

2024-04-30 16:19 UTC, coretl reviewed
Docs are artifacts of the build job, and can be downloaded and reviewed locally here: https://github.com/bluesky/ophyd-async/actions/runs/8898088019/artifacts/1461193368

2024-05-01 07:56 UTC, abbiemery commented
> Docs are artifacts of the build job, and can be downloaded and reviewed locally here: https://github.com/bluesky/ophyd-async/actions/runs/8898088019/artifacts/1461193368

This is not a great way to view this, can't I view on GH pages for this branch?

2024-05-01 08:08 UTC, abbiemery requested changes
I'd change the first line but other than that it seams to have fixed the formatting issues.

2024-05-01 08:08 UTC, abbiemery commented on README.md
"This is a python library" or "Ophyd async is a python..." for the line after the box of links. It is okay for the first line under the title to be a tag line and not correct English, but The rest of the read me should be.

2024-05-01 08:25 UTC, coretl commented
> > Docs are artifacts of the build job, and can be downloaded and reviewed locally here: https://github.com/bluesky/ophyd-async/actions/runs/8898088019/artifacts/1461193368
> 
> This is not a great way to view this, can't I view on GH pages for this branch?

No, pushing to gh-pages is what was bloating our repo size, so we removed it in the copier update. There's a possibility we could do this as part of https://github.com/DiamondLightSource/python-copier-template/issues/35

2024-05-01 08:51 UTC, evalott100 approved these changes

2024-05-01 08:51 UTC, merged