replace-ad_rw
bluesky/ophyd-async pull request #274
Opened 2024-05-02 08:48 UTC by ZohebShaikh

closes  #248

2024-05-02 08:52 UTC, ZohebShaikh commented
I think we can replace ad_r as well 
```
def ad_r(datatype: Type[T], prefix: str) -> SignalR[T]:
    return epics_signal_r(datatype, prefix + "_RBV")
```
it just calls to epics_signal_r internally

2024-05-02 09:09 UTC, coretl commented
> I think we can replace ad_r as well
> 
> ```
> def ad_r(datatype: Type[T], prefix: str) -> SignalR[T]:
>     return epics_signal_r(datatype, prefix + "_RBV")
> ```
> 
> it just calls to epics_signal_r internally

Yes please

2024-05-02 09:10 UTC, coretl reviewed
Looks good, please can you also replace `ad_r` and then delete the `utils.py` that contains it

2024-05-03 08:48 UTC, coretl requested changes

2024-05-03 08:48 UTC, coretl commented on src/ophyd_async/epics/areadetector/drivers/ad_base.py
> +        self.array_size_y = epics_signal_r(int, prefix + "ArraySizeY")
I notice that `ad_r` adds the `_RBV` suffix, so every replacement of it should do the same:
```suggestion
        self.array_size_y = epics_signal_r(int, prefix + "ArraySizeY_RBV")
```

2024-05-09 10:00 UTC, ZohebShaikh commented on src/ophyd_async/epics/areadetector/drivers/ad_base.py
> +        self.acquire = epics_signal_rw_rbv(bool, prefix + "Acquire_RBV")
I had a look at the function for `epics_signal_rw_rbv` it adds the suffix for it ..I have now removed it from the PR

2024-05-09 14:48 UTC, coretl approved these changes

2024-05-09 14:53 UTC, merged