remove things that go into the cookbook
bluesky/ophyd-async pull request #302
Opened 2024-05-13 08:13 UTC by stan-dot

2024-05-13 08:39 UTC, callumforrester requested changes

2024-05-13 08:39 UTC, callumforrester commented on .devcontainer/devcontainer.json
Please remove/raise as a separate PR

2024-05-13 08:39 UTC, callumforrester commented on docs/explanations/flyscanning.rst
> -Flyscanning (also known as hardware triggered scanning, asynchronous acquisition, and hardware synchronized scanning) is the practice of accelerating the rate of data collection by handing control ov
Will have to wait until after https://github.com/bluesky/bluesky-cookbook/pull/12 is merged, but I think we should then link to that page here

2024-05-13 08:43 UTC, stan-dot commented
`It should enable `motor trajectory scanning` and `multiple triggering rates<detectorsync_>` based around a base rate, and pausing/resuming scans. Scans should be modelled using scanspec_, which serves as a universal language for defining trajectory and time-resolved scans, and converted to the underlying format of the given motion controller. It should also be possible to define an `outer scan <outerscan_>`.`

docs/explanations/design-goals.rst contain a reference to those places. not sure how to handle this.

2024-05-13 09:42 UTC, callumforrester commented
For design goals, can also link to the new docs when they are published

2024-05-13 13:06 UTC, callumforrester commented
@stan-dot After https://github.com/bluesky/bluesky-cookbook/pull/12 is merged and the docs are published, they will be on Github pages. You can then link to them from here in order to fill missing pieces of information.

2024-05-13 16:32 UTC, stan-dot commented
what I mean @callumforrester  is that the design-goals.rst link to that removed flyscanning document
![image](https://github.com/bluesky/ophyd-async/assets/56644812/6436be26-84ec-4503-800c-cdf09936c3a2)

2024-05-15 15:54 UTC, stan-dot commented
from discussion: two step, publish one commit, then publish that new thing and make a new url-only (not markdown) link

2024-05-22 14:32 UTC, callumforrester approved these changes

2024-05-22 14:54 UTC, merged