Make PandA hdf resource_path relative to root
bluesky/ophyd-async pull request #380
Opened 2024-06-12 10:30 UTC by DiamondJoseph

PandA hdf resource_path was previously entire path: e.g.:

```json
    {
        "name": "stream_resource",
        "doc": {
            "uid": "f43ec9cc-8b7f-4579-897d-991bbb552364",
            "data_key": "i0",
            "spec": "AD_HDF5_SWMR_SLICE",
            "root": "/dls/i22/data/2024/cm37271-2/bluesky",
            "resource_path": "i22-3-i0-hdf.h5",
            "resource_kwargs": {
                "path": "/entry/data/data",
                "multiplier": 1,
                "timestamps": "/entry/instrument/NDAttributes/NDArrayTimeStamp"
            },
            "path_semantics": "posix",
            "run_start": "0362ddf7-8f09-4539-9288-eb303e66c059"
        }
    }
```

which doesn't match with the `expected root / resource_path = absolute_path`

```json
    {
        "name": "stream_resource",
        "doc": {
            "uid": "f43ec9cc-8b7f-4579-897d-991bbb552364",
            "data_key": "i0",
            "spec": "AD_HDF5_SWMR_SLICE",
            "root": "/dls/i22/data/2024/cm37271-2/bluesky",
            "resource_path": "i22-3-i0-hdf.h5",
            "resource_kwargs": {
                "path": "/entry/data/data",
                "multiplier": 1,
                "timestamps": "/entry/instrument/NDAttributes/NDArrayTimeStamp"
            },
            "path_semantics": "posix",
            "run_start": "0362ddf7-8f09-4539-9288-eb303e66c059"
        }
    }
```

2024-06-12 11:10 UTC, DiamondJoseph commented
Tagging @mrakitin to make sure this won't impact NA-side PandA filewriting expectations?

2024-06-12 11:49 UTC, coretl commented on src/ophyd_async/panda/writers/_hdf_writer.py
> +                file = Path(await self.panda_device.data.hdf_file_name.get_value())
There is already a PV that gives this:
https://github.com/PandABlocks/PandABlocks-ioc/blob/8e25d64cc97cfbf242a84c6ccbe600a39ed41c41/src/pandablocks_ioc/_hdf_ioc.py#L411-L413

2024-06-12 11:49 UTC, coretl commented on src/ophyd_async/panda/writers/_hdf_writer.py
> +                file = Path(await self.panda_device.data.hdf_file_name.get_value())
so
```python
    hdf_full_file_path: SignalR[str]
```
could be added alongside:
https://github.com/bluesky/ophyd-async/blob/b59d1e21c91a2697c36e519393f69a29b7601978/src/ophyd_async/panda/_common_blocks.py#L11-L12

2024-06-18 09:37 UTC, evalott100 requested changes

2024-06-18 09:37 UTC, evalott100 commented on src/ophyd_async/panda/writers/_panda_hdf_file.py
> +                resource_path=str(full_file_path.relative_to(directory_info.root)),
A test is erroring here because `root` is absolute, however `full_file_path` is "`.`".

2024-07-02 12:40 UTC, DiamondJoseph commented
Abandoning to prevent merge conflicts with #397 which should resolve this issue

2024-07-02 12:40 UTC, closed without merging