Tests for AreaDetector drivers/plugins to insure attributes are regularly named
bluesky/ophyd-async pull request #490
Opened 2024-07-25 10:56 UTC by subinsaji

Closes #80 

Recalling conversations with @coretl, in this PR we made changes to some names of attributes in order for tests to pass. New test that was created in here https://github.com/bluesky/ophyd-async/blob/5f49153e1bede552453183e2fa32a30b1fe50162/tests/epics/test_areadetector_subclass_naming.py#L1-L32

needs to import all subsequent subclasses from from `ophyd_async.epics` for test coverage. If a developer adds more plugins or drivers, the developer must also import them.

2024-07-26 08:06 UTC, coretl requested changes

2024-07-26 08:06 UTC, coretl commented on src/ophyd_async/epics/adpilatus/_pilatus_io.py
> +        self.armed_for_triggers = epics_signal_r(bool, prefix + "ArmedForTriggers")
The PV is set in stone, we can only change the attribute name to match...
```suggestion
        self.armed = epics_signal_r(bool, prefix + "Armed")
```

2024-07-26 08:09 UTC, coretl commented
@DiamondJoseph @callumforrester @jwlodek this PR will mean that all areaDetector classes are guaranteed to have predictable attribute names. E.g. the PV `$(P)$(R)MyAttribute` will be called `self.my_attribute`. This is the mapping that PVI will do by default, although if we *really* don't like the PV name we could put an exception in for particular cases.

Are we happy to keep the slightly more obtuse attribute names so we get uniformity and predictability?

2024-07-29 10:45 UTC, DiamondJoseph commented
consistency >> all other concerns IMO

2024-07-29 13:25 UTC, jwlodek commented
This is OK with me as well.

2024-07-29 17:33 UTC, coretl approved these changes

2024-07-30 08:46 UTC, merged