make motor locatable
bluesky/ophyd-async pull request #541
Opened 2024-08-23 07:49 UTC by stan-dot

2024-08-23 07:50 UTC, dperl-dls requested changes
Looks good, would you please add a test?

2024-08-23 08:04 UTC, stan-dot commented
> Looks good, would you please add a test and fix the inheritance order?


ah yes I forgot it's not a set but an ordered list. how should the inheritance order look like?

2024-08-23 08:06 UTC, stan-dot commented
also I realized if sim motor actions are instant I might not get the assert on the difference between the readback and set point. there should be a way to do this, investigating...

2024-08-23 08:19 UTC, dperl-dls commented
Not sure, but some way that https://docs.python.org/3/howto/mro.html can get a consistent order out of `HasName, Movable, Stoppable, Flyable, Preparable, Locatable`.

I think the issue is likely that several of these inherit each other already, so I would try:

`StandardReadable, Flyable, Locatable, Preparable, Stoppable` since this covers all the methods.

You can stop the sim motor from moving with
```python
with ophyd_async.core.mock_puts_blocked(motor.signal):
    < do the set, assert, etc. >
```

2024-08-23 08:24 UTC, stan-dot commented
thanks, trying this now

2024-08-23 12:49 UTC, stan-dot commented
I get this
```python
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/xma12127/projects/forks/ophyd-async/tests/epics/test_motor.py", line 324, in test_locatable
    with mock_puts_blocked(sim_motor.user_setpoint):
TypeError: '_AsyncGeneratorContextManager' object does not support the context manager protocol

```

but it *is* a SignalRW, just like the only other example of the use of this method that I could find - in `tests/core/test_mock_signal_backend.py`

2024-08-23 13:08 UTC, dperl-dls reviewed
That sim motor is not the one from the demo

2024-08-23 13:08 UTC, dperl-dls commented on tests/epics/test_motor.py
> +    assert (await sim_motor.locate())["readback"] == 10
```suggestion
async def test_locatable(sim_motor: motor.Motor) -> None:
    callback_on_mock_put(
        sim_motor.user_setpoint,
        lambda x, *_, **__: set_mock_value(sim_motor.user_readback, x),
    )
    assert (await sim_motor.locate())["readback"] == 0
    async with mock_puts_blocked(sim_motor.user_setpoint):
        move_status = sim_motor.set(10)
        assert (await sim_motor.locate())["readback"] == 0
    await move_status
    assert (await sim_motor.locate())["readback"] == 10
```

2024-08-23 16:02 UTC, stan-dot commented on tests/epics/test_motor.py
> +    assert (await sim_motor.locate())["readback"] == 10
thanks, it worked!

2024-08-27 08:46 UTC, dperl-dls approved these changes
lgtm, thanks

2024-08-27 10:26 UTC, merged