549 support multi run in standarddetectorprepares
bluesky/ophyd-async pull request #568
Opened 2024-09-11 11:20 UTC by ZohebShaikh

2024-09-12 16:04 UTC, coretl requested changes

2024-09-12 16:04 UTC, coretl commented on src/ophyd_async/epics/adpilatus/_pilatus_controller.py
>              timeout=DEFAULT_TIMEOUT,
This needs moving to `arm()`

2024-09-13 09:37 UTC, ZohebShaikh commented on src/ophyd_async/epics/adkinetix/_kinetix_controller.py
> +        )
https://github.com/bluesky/ophyd-async/pull/568/commits/338f946769e65408bc2dc7a6430fee7548a43df0 did you mean something like this ?

2024-09-13 09:43 UTC, coretl commented on src/ophyd_async/epics/adpilatus/_pilatus_controller.py
> +            ),
This was fine as it was...

2024-09-13 09:44 UTC, coretl commented on src/ophyd_async/fastcs/panda/_control.py
> +        )
Same here

2024-09-13 10:17 UTC, coretl approved these changes

2024-09-13 10:27 UTC, merged